steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/dev-mgmt-ibu-cc-ea/spring-boot', '.']
images: ['gcr.io/dev-mgmt-ibu-cc-ea/spring-boot']
